travis:
  secure:
    BINSTAR_TOKEN: hyCI6OghG2Alr8Z7Z1rPIRWhOfEWGJOLEKT5cvTA96K3WaKWRJHd+qH+T4k8VvArFhpdZ98ove54mO0bnMot1iCqRAw6gRo7NnYTxS1hUGjVasJJYCQwrTaY91MuZzvh6T5DqO2V35IaQw44qpvZ9DdYeHUPZxvxE4d3a2HhAxnQdUDI6hl/1YFOl9DMj9wOjdHirNaAEP77azSOCgWkCAhoC013Z6rFnq5kCtMF3+H8nrqglnNQq8ZEXpIT1BY16lgaCJQnN6v2UGgPfsMViqe1wsNtbumzfjCLaWPGVfu3/R8gRZyr21llOfcgJOc6h/a3IObQrUk/zNTy3Wm/q6TMU4t0xJkeWHrmD5x0+2TBjSZ2mu23Ui/+JUqkpOkDOaV4aTJlUR2Q5gw1kmGhmPIdIwWDY0JstfUPBT26tiv79nk70hPFZsSQIK+i4+TvW8f0JFDKzqfgHCwhaLD5tLWiu1X27Vk+1m0jyV9IP8AiUcKJCueI2z6g/o8d72kV8I7pROwtaHZM8eKUQqmqIps/jFU3bmt1aSl4RHw7PgAVRyUDJSS5NBJzzk/nY/3DE2BB4XxM1OxuIM+Qll+tPRAlazFzLPz5VggU6jEO1FJGZ7lBWnpeaKfZCjiS7JnGVzET1TaVyhtyQN3kFUmDiCX8ZHORzF2B25Da9v3ruz8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
